"""empty message

Revision ID: 1b633c55afb2
Revises: 
Create Date: 2024-05-28 21:47:36.884185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b633c55afb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('media_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('Admin', 'CUSTOMER', name='rolenames'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('temp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temp_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_user_email'), ['email'], unique=True)

    op.create_table('vasset_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vasset_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_vasset_user_username'), ['username'], unique=True)

    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=6), nullable=True),
    sa.Column('vasset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PASSPORT', 'NIN', 'DRIVERS_LICENCE', 'NATIONAL_ID', name='identificationtype'), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('picture_id', sa.Integer(), nullable=True),
    sa.Column('vasset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['picture_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('next_of_kin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('firstname', sa.String(length=200), nullable=True),
    sa.Column('lastname', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('vasset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('uri', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('vasset_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=200), nullable=True),
    sa.Column('lastname', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_picture_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=50), nullable=True),
    sa.Column('_bvn', sa.Integer(), nullable=True),
    sa.Column('vasset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_picture_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_bvn')
    )
    op.create_table('real_estates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], )
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vasset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vasset_user_id'], ['vasset_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_new_features', sa.Boolean(), nullable=True),
    sa.Column('email_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('email_money_earned', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_features', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('in_app_money_earned', sa.Boolean(), nullable=True),
    sa.Column('push_new_features', sa.Boolean(), nullable=True),
    sa.Column('push_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('push_money_earned', sa.Boolean(), nullable=True),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two_factor_method', sa.Enum('PHONE', 'EMAIL', 'GOOGLE_AUTH_APP', 'NONE', name='twofactormethod'), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(length=150), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    op.drop_table('security_setting')
    op.drop_table('notification_preference')
    op.drop_table('user_settings')
    op.drop_table('user_roles')
    op.drop_table('stocks')
    op.drop_table('real_estates')
    op.drop_table('profile')
    op.drop_table('one_time_token')
    op.drop_table('nfts')
    op.drop_table('next_of_kin')
    op.drop_table('identification')
    op.drop_table('cryptos')
    op.drop_table('businesses')
    op.drop_table('address')
    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vasset_user_username'))
        batch_op.drop_index(batch_op.f('ix_vasset_user_email'))

    op.drop_table('vasset_user')
    with op.batch_alter_table('temp_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_user_email'))

    op.drop_table('temp_user')
    op.drop_table('role')
    op.drop_table('media')
    # ### end Alembic commands ###
