"""empty message

Revision ID: 454eeeb11d8d
Revises: c028df1ce042
Create Date: 2024-05-30 18:19:20.542005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454eeeb11d8d'
down_revision = 'c028df1ce042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.drop_constraint('identification_type_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identification', schema=None) as batch_op:
        batch_op.create_unique_constraint('identification_type_key', ['type'])

    # ### end Alembic commands ###
