"""empty message

Revision ID: 476cb35a86f1
Revises: ef41f467f47e
Create Date: 2024-06-16 15:38:36.219354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476cb35a86f1'
down_revision = 'ef41f467f47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('businesses_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.drop_constraint('cryptos_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_constraint('nfts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('real_estates', schema=None) as batch_op:
        batch_op.drop_constraint('real_estates_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.drop_constraint('social_media_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint('stocks_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.drop_constraint('youtube_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vasset_user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('youtube_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('stocks_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('social_media_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('real_estates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('real_estates_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nfts_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cryptos_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('businesses_user_id_fkey', 'vasset_user', ['user_id'], ['id'])

    # ### end Alembic commands ###
