"""empty message

Revision ID: 68d163581395
Revises: 476cb35a86f1
Create Date: 2024-06-23 15:52:18.404391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d163581395'
down_revision = '476cb35a86f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coin_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('coin_type')
        batch_op.drop_column('wallet_type')

    # ### end Alembic commands ###
