"""Increase length of password field

Revision ID: c028df1ce042
Revises: 1b633c55afb2
Create Date: 2024-05-28 22:22:00.994865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c028df1ce042'
down_revision = '1b633c55afb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('next_of_kin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('next_of_kin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
