"""empty message

Revision ID: dbaf099f95eb
Revises: fe8aca3345ce
Create Date: 2024-06-09 18:48:19.845200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaf099f95eb'
down_revision = 'fe8aca3345ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('wallet_address', sa.String(length=120), nullable=False),
    sa.Column('screenshot_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vasset_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vasset_user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    op.drop_table('transactions')
    # ### end Alembic commands ###
