"""empty message

Revision ID: ef41f467f47e
Revises: 5e0258d7c480
Create Date: 2024-06-16 14:22:20.444743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef41f467f47e'
down_revision = '5e0258d7c480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cryptos', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
