"""empty message

Revision ID: fe8aca3345ce
Revises: 
Create Date: 2024-06-07 13:16:50.122370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8aca3345ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
